import { useLocalSearchParams, router } from "expo-router";
import { useState } from "react";
import { AudioModule, RecordingPresets, setAudioModeAsync, useAudioRecorder, useAudioRecorderState } from "expo-audio";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useKeepAwake } from "expo-keep-awake";
import { GhostButton, PrimaryButton } from "../components/PrimaryButton";
import { Screen } from "../components/Screen";
import { colors } from "../lib/theme";

const initialSegments = [
  { id: "1", speaker: "مايا حداد", language: "العربية", original: "أقترح أن نبدأ بنطاق الإطلاق، ثم نراجع المراحل مع الفريق.", translated: "I suggest we start with the launch scope, then review the milestones with the team." },
  { id: "2", speaker: "Daniel Brooks", language: "English", original: "That works for me. I need clarity on the pilot markets before we lock the timeline.", translated: "هذا مناسب لي. أحتاج إلى وضوح بشأن أسواق التجربة قبل تثبيت الجدول الزمني." },
];

export default function MeetingScreen() {
  useKeepAwake(); const params = useLocalSearchParams<{ title?: string; speaking?: string; display?: string }>(); const [muted, setMuted] = useState(false); const [listening, setListening] = useState(false); const [draft, setDraft] = useState(""); const [segments, setSegments] = useState(initialSegments); const recorder = useAudioRecorder(RecordingPresets.HIGH_QUALITY); const recorderState = useAudioRecorderState(recorder);
  const addSegment = () => setSegments(current => [...current, { id: String(Date.now()), speaker: "أنت", language: params.speaking === "en" ? "English" : "العربية", original: params.speaking === "en" ? "I will prepare the onboarding flow for review." : "سأجهز تدفق التهيئة لمراجعته مع الفريق.", translated: params.speaking === "en" ? "سأجهز تدفق التهيئة لمراجعته مع الفريق." : "I will prepare the onboarding flow for review." }]);
  const toggleRecording = async () => { try { if (recorderState.isRecording) { await recorder.stop(); setListening(false); Alert.alert("توقف الالتقاط", "سيرسل تدفق الإنتاج المقطع إلى خدمة النسخ والترجمة عند ربط API."); return; } const permission = await AudioModule.requestRecordingPermissionsAsync(); if (!permission.granted) { Alert.alert("صلاحية مطلوبة", "اسمح للتطبيق بالوصول إلى الميكروفون لتشغيل النسخ الحي."); return; } await setAudioModeAsync({ playsInSilentMode: true, allowsRecording: true }); await recorder.prepareToRecordAsync(); recorder.record(); setListening(true); } catch { Alert.alert("تعذر تشغيل الميكروفون", "تحقق من إعدادات الصوت في الجهاز ثم حاول مجددًا."); } };
  return <Screen><View style={styles.root}><View style={styles.header}><GhostButton title="إنهاء" onPress={() => router.push("/minutes")} /><View><Text style={styles.meetingTitle}>{params.title ?? "مزامنة خطة الإطلاق"}</Text><Text style={styles.meta}>3 مشاركين · اجتماع مباشر</Text></View></View><View style={styles.state}><View style={[styles.liveDot, listening && styles.liveDotActive]} /><Text style={styles.stateText}>{listening ? "التقاط الصوت يعمل" : "النص الحي متوقف"}</Text></View><Text style={styles.heading}>النص والترجمة الفورية</Text><View style={styles.labels}><Text style={styles.label}>النص الأصلي</Text><Text style={[styles.label, styles.translationLabel]}>ترجمتك المباشرة</Text></View><FlatList data={segments} keyExtractor={item => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.segment}><View style={styles.segmentHead}><View style={styles.avatar}><Text style={styles.avatarText}>{item.speaker.slice(0, 1)}</Text></View><View style={styles.segmentName}><Text style={styles.name}>{item.speaker}</Text><Text style={styles.language}>{item.language} · الآن</Text></View></View><View style={styles.dual}><Text style={[styles.original, item.language === "English" && styles.ltr]}>{item.original}</Text><Text style={styles.translated}>{item.translated}</Text></View></View>} ListFooterComponent={<GhostButton title="إضافة مقطع مترجم تجريبي" onPress={addSegment} />} /><View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="اكتب رسالة مترجمة…" placeholderTextColor={colors.muted} style={styles.message} textAlign="right" /><Pressable onPress={() => { if (draft.trim()) { Alert.alert("أُرسلت الرسالة", "ستُراجع الترجمة قبل الإرسال في الربط الخادمي."); setDraft(""); } }} style={styles.send}><Text style={styles.sendText}>إرسال</Text></Pressable></View><View style={styles.controls}><Pressable onPress={() => setMuted(value => !value)} style={[styles.control, muted && styles.activeControl]}><Text style={styles.controlText}>{muted ? "إلغاء الكتم" : "كتم"}</Text></Pressable><Pressable onPress={() => void toggleRecording()} style={[styles.control, listening && styles.activeControl]}><Text style={styles.controlText}>{listening ? "إيقاف الالتقاط" : "تشغيل الالتقاط"}</Text></Pressable><PrimaryButton title="قراءة آخر ترجمة" onPress={() => Alert.alert("قراءة الترجمة", "سيستخدم التطبيق صوت النظام المختار عند ربط طبقة TTS الأصلية.")} style={styles.readButton} /></View></View></Screen>;
}

const styles = StyleSheet.create({ root: { flex: 1, padding: 16 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, meetingTitle: { color: colors.ink, fontSize: 15, fontWeight: "900", textAlign: "right" }, meta: { color: colors.muted, fontSize: 10, textAlign: "right", marginTop: 4 }, state: { alignSelf: "flex-end", flexDirection: "row", alignItems: "center", gap: 6, borderRadius: 99, backgroundColor: colors.surface, paddingHorizontal: 10, paddingVertical: 6, marginTop: 15 }, liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: "#94A3B8" }, liveDotActive: { backgroundColor: colors.rose }, stateText: { color: colors.muted, fontSize: 10, fontWeight: "800" }, heading: { color: colors.ink, fontSize: 23, fontWeight: "900", textAlign: "right", marginTop: 10 }, labels: { flexDirection: "row", gap: 8, marginTop: 15 }, label: { flex: 1, borderRadius: 8, backgroundColor: "#F8FAFC", padding: 8, color: colors.muted, fontSize: 10, fontWeight: "800", textAlign: "right" }, translationLabel: { backgroundColor: colors.lavender, color: colors.indigo }, list: { gap: 10, paddingTop: 10, paddingBottom: 8 }, segment: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 18, padding: 13, gap: 10 }, segmentHead: { flexDirection: "row", justifyContent: "flex-end", gap: 8, alignItems: "center" }, avatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: "#FEF3C7", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#92400E", fontSize: 12, fontWeight: "900" }, segmentName: { alignItems: "flex-end" }, name: { color: colors.ink, fontSize: 12, fontWeight: "900" }, language: { color: colors.muted, fontSize: 9, marginTop: 2 }, dual: { gap: 8 }, original: { borderRadius: 12, backgroundColor: "#F8FAFC", padding: 11, color: colors.ink, fontSize: 13, lineHeight: 21, textAlign: "right" }, ltr: { textAlign: "left" }, translated: { borderRadius: 12, backgroundColor: colors.lavender, padding: 11, color: colors.ink, fontSize: 13, lineHeight: 21, textAlign: "right" }, composer: { flexDirection: "row", alignItems: "center", gap: 8, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 16, padding: 8, marginTop: 6 }, message: { flex: 1, minHeight: 37, color: colors.ink, fontSize: 13 }, send: { borderRadius: 11, backgroundColor: colors.ink, paddingHorizontal: 12, paddingVertical: 10 }, sendText: { color: "white", fontSize: 11, fontWeight: "800" }, controls: { flexDirection: "row", gap: 8, marginTop: 10, alignItems: "center" }, control: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 11 }, activeControl: { borderColor: "#C7D2FE", backgroundColor: colors.lavender }, controlText: { color: colors.ink, fontSize: 11, fontWeight: "800" }, readButton: { flex: 1, height: 42, borderRadius: 12 } });
